# core/brain.py
import re
import os
import subprocess
from skills import open_apps, weather_info, reminder_manager, coding_assistant, system_controls
from knowledge.llm_connector import ask_gpt, get_llm_status, set_offline_mode

def process_command(command):
    command_lower = command.lower().strip()
    original_command = command.strip()

    # Enhanced intent routing with better pattern matching
    # System command execution should be checked before app opening so 'run ...' works
    if any(keyword in command_lower for keyword in ["run", "execute", "cmd", "command"]):
        return handle_system_commands(command)
    if any(keyword in command_lower for keyword in ["open", "launch", "start"]):
        return open_apps.handle(command)
    elif "weather" in command_lower:
        return weather_info.handle(command)
    elif "remind" in command_lower:
        return reminder_manager.handle(command)
    # Installation help should be routed before coding intents so 'help install vs code' works
    elif "help install" in command_lower or "install help" in command_lower:
        return handle_installation_help(command)
    # LLM status / offline toggles
    elif command_lower in ["llm status", "ai status", "model status"]:
        return get_llm_status()
    elif command_lower in ["go offline", "llm offline", "ai offline"]:
        return set_offline_mode(True)
    elif command_lower in ["go online", "llm online", "ai online"]:
        return set_offline_mode(False)
    # System controls (timer, shutdown, restart, sleep, lock, logoff, wifi/bluetooth)
    elif any(k in command_lower for k in [
        "timer", "timmer", "set timer", "set timmer", "countdown", "alarm in", "set alarm", "remind me in",
        "shutdown", "power off", "turn off", "restart", "reboot", "sleep", "suspend", "lock", "lock screen",
        "logoff", "log out", "sign out", "stop alarm", "stop timer", "stop ringing", "silence alarm", "dismiss alarm",
        "volume", "mute", "unmute", "sound", "increase volume", "decrease volume",
        "brightness", "screen brightness", "display brightness", "increase brightness", "decrease brightness",
        "bluetooth", "bt", "wifi", "wi-fi", "wi fi", "wlan"
    ]):
        return system_controls.handle(command)
    elif "create file" in command_lower and not any(ext in command_lower for ext in ["python", "html", "css", "javascript", "json"]):
        return handle_coding_commands(command)
    elif any(keyword in command_lower for keyword in ["create", "write", "code", "generate", "make", "python", "html", "css", "javascript", "json"]):
        return coding_assistant.handle(command)
    elif any(keyword in command_lower for keyword in ["list", "show", "dir", "ls"]):
        return handle_file_operations(command)
    elif any(keyword in command_lower for keyword in ["cd", "navigate", "go to"]):
        return handle_navigation(command)
    elif command_lower in ["quit", "exit", "bye", "goodbye"]:
        return "Goodbye! Have a great day! 👋"
    else:
        return ask_gpt(command)

def handle_coding_commands(command):
    """Handle coding and file creation commands"""
    command_lower = command.lower()
    
    if "create file" in command_lower or "make file" in command_lower:
        # Extract filename from command
        filename = extract_filename(command)
        if filename:
            try:
                with open(filename, 'w') as f:
                    f.write("# Created by Personal Assistant\n")
                return f"✅ Created file: {filename}"
            except Exception as e:
                return f"❌ Error creating file: {str(e)}"
    
    elif "create folder" in command_lower or "make directory" in command_lower:
        folder_name = extract_folder_name(command)
        if folder_name:
            try:
                os.makedirs(folder_name, exist_ok=True)
                return f"✅ Created folder: {folder_name}"
            except Exception as e:
                return f"❌ Error creating folder: {str(e)}"
    
    elif "python script" in command_lower or "py file" in command_lower:
        filename = extract_filename(command) or "script.py"
        if not filename.endswith('.py'):
            filename += '.py'
        try:
            with open(filename, 'w') as f:
                f.write("#!/usr/bin/env python3\n# Generated by Personal Assistant\n\n")
            return f"✅ Created Python script: {filename}"
        except Exception as e:
            return f"❌ Error creating Python script: {str(e)}"
    
    return "I can help you create files, folders, and Python scripts. Try: 'create file filename.txt' or 'create Python script'"

def handle_file_operations(command):
    """Handle file listing and directory operations"""
    command_lower = command.lower()
    
    if "list files" in command_lower or "show files" in command_lower or "ls" in command_lower:
        try:
            files = os.listdir('.')
            if files:
                file_list = "\n".join([f"📄 {f}" for f in files])
                return f"📁 Current directory contents:\n{file_list}"
            else:
                return "📁 Directory is empty"
        except Exception as e:
            return f"❌ Error listing files: {str(e)}"
    
    return "I can list files in the current directory. Try: 'list files' or 'show files'"

def handle_navigation(command):
    """Handle directory navigation"""
    command_lower = command.lower()
    
    if "cd" in command_lower or "navigate" in command_lower:
        # Extract directory path
        path = extract_path(command)
        if path:
            try:
                os.chdir(path)
                return f"✅ Navigated to: {os.getcwd()}"
            except Exception as e:
                return f"❌ Error navigating to {path}: {str(e)}"
    
    return "I can help you navigate directories. Try: 'cd folder_name' or 'navigate to path'"

def handle_system_commands(command):
    """Handle system command execution"""
    command_lower = command.lower()
    
    if "run" in command_lower or "execute" in command_lower:
        # Extract the actual command to run
        cmd = extract_command(command)
        if cmd:
            try:
                result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=30)
                if result.returncode == 0:
                    return f"✅ Command executed successfully:\n{result.stdout}"
                else:
                    return f"❌ Command failed:\n{result.stderr}"
            except subprocess.TimeoutExpired:
                return "❌ Command timed out"
            except Exception as e:
                return f"❌ Error executing command: {str(e)}"
    
    return "I can execute system commands. Try: 'run dir' or 'execute python --version'"

def extract_filename(command):
    """Extract filename from command"""
    patterns = [
        r'create file (\S+)',
        r'make file (\S+)',
        r'file (\S+)',
    ]
    for pattern in patterns:
        match = re.search(pattern, command.lower())
        if match:
            return match.group(1)
    return None

def extract_folder_name(command):
    """Extract folder name from command"""
    patterns = [
        r'create folder (\S+)',
        r'make directory (\S+)',
        r'folder (\S+)',
    ]
    for pattern in patterns:
        match = re.search(pattern, command.lower())
        if match:
            return match.group(1)
    return None

def extract_path(command):
    """Extract path from navigation command"""
    patterns = [
        r'cd (\S+)',
        r'navigate to (\S+)',
        r'go to (\S+)',
    ]
    for pattern in patterns:
        match = re.search(pattern, command.lower())
        if match:
            return match.group(1)
    return None

def extract_command(command):
    """Extract system command to execute"""
    patterns = [
        r'run (.+)',
        r'execute (.+)',
        r'command (.+)',
    ]
    for pattern in patterns:
        match = re.search(pattern, command.lower())
        if match:
            return match.group(1)
    return None

def handle_installation_help(command):
    """Provide installation help for applications"""
    command_lower = command.lower()
    
    installation_guides = {
        "vs code": """💻 **VS Code Installation Help**
1. Download from: https://code.visualstudio.com/
2. Run the installer
3. Add to PATH during installation
4. Restart your terminal/command prompt
5. Try: 'open vs code' again""",
        
        "postman": """📮 **Postman Installation Help**
1. Download from: https://www.postman.com/downloads/
2. Run the installer
3. Launch Postman from Start Menu
4. Try: 'open postman' again""",
        
        "intellij": """🧠 **IntelliJ IDEA Installation Help**
1. Download from: https://www.jetbrains.com/idea/
2. Run the installer
3. Add to PATH if prompted
4. Try: 'open intellij' again""",
        
        "eclipse": """🌙 **Eclipse Installation Help**
1. Download from: https://www.eclipse.org/downloads/
2. Extract to a folder
3. Run eclipse.exe
4. Try: 'open eclipse' again""",
        
        "android studio": """🤖 **Android Studio Installation Help**
1. Download from: https://developer.android.com/studio
2. Run the installer
3. Follow setup wizard
4. Try: 'open android studio' again""",
        
        "figma": """🎨 **Figma Installation Help**
1. Download from: https://www.figma.com/downloads/
2. Run the installer
3. Launch from Start Menu
4. Try: 'open figma' again""",
        
        "docker": """🐳 **Docker Desktop Installation Help**
1. Download from: https://www.docker.com/products/docker-desktop
2. Run the installer
3. Restart your computer
4. Try: 'open docker' again""",
        
        "git": """🐙 **Git Installation Help**
1. Download from: https://git-scm.com/
2. Run the installer
3. Add to PATH during installation
4. Try: 'open git bash' again""",
        
        "node": """🟢 **Node.js Installation Help**
1. Download from: https://nodejs.org/
2. Run the installer
3. Restart your terminal
4. Try: 'open node' again""",
    }
    
    # Extract app name from command
    for app_name, guide in installation_guides.items():
        if app_name in command_lower:
            return guide
    
    # General installation help
    return """🛠️ **Application Installation Help**

I can help you install these popular applications:

💻 **Development Tools:**
• VS Code - Code editor
• Postman - API testing
• IntelliJ IDEA - Java IDE
• Eclipse - Java IDE
• Android Studio - Android development

🎨 **Design Tools:**
• Figma - UI/UX design
• Sketch - Design tool (macOS only)

🐙 **Development Tools:**
• Git - Version control
• Docker - Containerization
• Node.js - JavaScript runtime

**Usage:** 'help install [app name]'
**Example:** 'help install vs code'

💡 Most applications will provide download links and installation instructions!"""